"""PDF report, built from a run's report.json payload.

Reading report.json (rather than a live ScanFindings) is deliberate: it's the
one artifact every past run already has on disk, so the same code produces a
PDF for a scan that finished months ago and for one that just ended.

Optional: needs the [pdf] extra (reportlab). reportlab ships its own
Bitstream Vera TTF, which covers Turkish/Latin-Extended glyphs, so the PDF
looks the same on macOS, Linux and Windows with no system font hunting.
"""
from __future__ import annotations

import io
import os
import re
from datetime import datetime

try:
    import reportlab
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_LEFT
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont
    from reportlab.platypus import BaseDocTemplate, Frame, PageBreak, PageTemplate, Paragraph, Spacer, Table, TableStyle
    PDF_AVAILABLE = True
except ImportError:  # optional dependency, see pyproject.toml [pdf]
    PDF_AVAILABLE = False

_SUPPORTED_LANGS = {"en", "tr"}
_FONT = "MetaScout"
_FONT_BOLD = "MetaScout-Bold"

# Print-friendly palette: light page, same accent hues as the HTML report.
_INK = "#1b2230"
_MUTED = "#6b7688"
_LINE = "#dde3ec"
_ACCENT = "#2563d8"
_BAD = "#c0392b"
_WARN = "#b26a12"
_GOOD = "#1f8a4c"

_CATEGORIES = ["usernames", "emails", "software", "operating_systems", "internal_paths",
               "servers_and_printers", "geolocation", "classification_labels"]
_CRITICAL_CONTENT = {"tc_kimlik", "iban", "credit_card"}
# Kept in step with the analyzer's own RESTRICTED_LABEL_RE, but re-declared
# here so a PDF can be built from a report.json without importing the
# analyzer's scanning machinery.
_RESTRICTED_LABEL_RE = re.compile(
    r"confidential|restricted|secret|internal|private|classified|nato\s|"
    r"gizli|özel|hizmete|kişiye|tasnifli",
    re.IGNORECASE,
)
# Tables of every document/error get long; keep the PDF a report, not a dump.
_MAX_ROWS = 400

_STRINGS = {
    "en": {
        "title": "Metadata Leak Report",
        "subtitle": "Document discovery & metadata reconnaissance",
        "targets": "Target(s)", "scanned": "Scanned", "generated": "Generated",
        "risk_none": "No Findings", "risk_low": "Low Risk", "risk_medium": "Medium Risk", "risk_high": "High Risk",
        "summary": "Summary",
        "stat_documents": "Documents found", "stat_with_metadata": "With metadata",
        "stat_findings": "Unique findings", "stat_archive": "From archive",
        "per_target": "Documents per target", "col_target": "Target", "col_documents": "Documents read",
        "usernames": "Usernames", "emails": "Email Addresses", "software": "Software & Versions",
        "operating_systems": "Operating Systems", "internal_paths": "Internal File Paths",
        "servers_and_printers": "Servers & Printers", "geolocation": "Geolocation (GPS)",
        "classification_labels": "Classification Labels",
        "restricted_note": "Some of these documents carry a label saying they are not meant to be public. "
                           "The label is in the document's own metadata; the document itself is published.",
        "col_value": "Value", "col_field": "Metadata field", "col_docs": "Docs", "col_seen": "First seen in",
        "content_scan": "Content Scan (personal/critical data)",
        "col_category": "Category", "col_masked": "Value (masked)", "col_document": "Document",
        "content_note": "Heuristic hits — verify each one manually.",
        "critical_files": "Critical / Sensitive Files",
        "documents": "Documents", "col_url": "URL", "col_type": "Type", "col_status": "Status",
        "status_ok": "ok", "status_error": "error",
        "archive_tag": "ARCHIVE",
        "archive_note": "{n} document(s) are no longer live on the site; the copy came from the Wayback "
                        "Machine archive and is tagged ARCHIVE below. Removed from the site, still public "
                        "through the archive.",
        "errors": "Errors", "errors_note": "Documents that could not be downloaded or read.",
        "empty": "No findings in this category.",
        "truncated": "… and {n} more (see report.json for the full list).",
        "footer": "Generated by MetaScout {version} · for authorized security assessments only",
        "page": "Page {page}",
        "intro": "{docs} document(s) discovered, metadata was extracted from {with_meta}, for a total of "
                 "{findings} unique finding(s).",
    },
    "tr": {
        "title": "Metadata Sızıntı Raporu",
        "subtitle": "Belge keşfi & metadata sızıntı analizi",
        "targets": "Hedef(ler)", "scanned": "Tarama tarihi", "generated": "Oluşturulma",
        "risk_none": "Bulgu Yok", "risk_low": "Düşük Risk", "risk_medium": "Orta Risk", "risk_high": "Yüksek Risk",
        "summary": "Özet",
        "stat_documents": "Belge bulundu", "stat_with_metadata": "Metadata içeren",
        "stat_findings": "Benzersiz bulgu", "stat_archive": "Arşivden gelen",
        "per_target": "Hedef başına belge", "col_target": "Hedef", "col_documents": "Metadata okunan",
        "usernames": "Kullanıcı Adları", "emails": "E-posta Adresleri", "software": "Yazılım & Sürümler",
        "operating_systems": "İşletim Sistemleri", "internal_paths": "İç Dosya Yolları",
        "servers_and_printers": "Sunucular & Yazıcılar", "geolocation": "Konum (GPS)",
        "classification_labels": "Gizlilik Etiketleri",
        "restricted_note": "Bu belgelerin bir kısmı, herkese açık olmaması gerektiğini söyleyen bir gizlilik "
                           "etiketi taşıyor. Etiket belgenin metadata'sında duruyor; belgenin kendisi yayında.",
        "col_value": "Değer", "col_field": "Metadata alanı", "col_docs": "Belge", "col_seen": "İlk görüldüğü belge",
        "content_scan": "İçerik Taraması (kişisel/kritik veri)",
        "col_category": "Kategori", "col_masked": "Değer (maskeli)", "col_document": "Belge",
        "content_note": "Sezgisel bulgular — her birini elle doğrulayın.",
        "critical_files": "Kritik / Hassas Dosyalar",
        "documents": "Belgeler", "col_url": "URL", "col_type": "Tür", "col_status": "Durum",
        "status_ok": "tamam", "status_error": "hata",
        "archive_tag": "ARŞİV",
        "archive_note": "{n} belge sitede artık yayında değil; kopya Wayback Machine arşivinden alındı ve "
                        "aşağıda ARŞİV etiketiyle işaretlendi. Siteden kaldırılmış olsalar da arşiv "
                        "üzerinden hâlâ herkese açıklar.",
        "errors": "Hatalar", "errors_note": "İndirilemeyen veya okunamayan belgeler.",
        "empty": "Bu kategoride bulgu yok.",
        "truncated": "… ve {n} kayıt daha (tam liste için report.json).",
        "footer": "MetaScout {version} tarafından üretildi · yalnızca yetkili güvenlik değerlendirmeleri için",
        "page": "Sayfa {page}",
        "intro": "{docs} belge keşfedildi, {with_meta} tanesinden metadata çıkarıldı ve toplam "
                 "{findings} benzersiz bulgu tespit edildi.",
    },
}


class PdfDependencyMissing(RuntimeError):
    """reportlab isn't installed — see the [pdf] extra."""


def _register_fonts() -> None:
    if _FONT in pdfmetrics.getRegisteredFontNames():
        return
    fonts_dir = os.path.join(os.path.dirname(reportlab.__file__), "fonts")
    pdfmetrics.registerFont(TTFont(_FONT, os.path.join(fonts_dir, "Vera.ttf")))
    pdfmetrics.registerFont(TTFont(_FONT_BOLD, os.path.join(fonts_dir, "VeraBd.ttf")))
    pdfmetrics.registerFontFamily(_FONT, normal=_FONT, bold=_FONT_BOLD)


def _styles() -> dict:
    base = ParagraphStyle("body", fontName=_FONT, fontSize=8.5, leading=11.5, textColor=colors.HexColor(_INK), alignment=TA_LEFT)
    return {
        "title": ParagraphStyle("title", parent=base, fontName=_FONT_BOLD, fontSize=20, leading=24, spaceAfter=2),
        "subtitle": ParagraphStyle("subtitle", parent=base, fontSize=9.5, textColor=colors.HexColor(_MUTED), spaceAfter=10),
        "h2": ParagraphStyle("h2", parent=base, fontName=_FONT_BOLD, fontSize=12.5, leading=16, spaceBefore=14, spaceAfter=6),
        "body": base,
        "muted": ParagraphStyle("muted", parent=base, textColor=colors.HexColor(_MUTED)),
        "cell": ParagraphStyle("cell", parent=base, fontSize=8),
        "cell_mono": ParagraphStyle("cell_mono", parent=base, fontSize=7.6, leading=10),
        "stat_num": ParagraphStyle("stat_num", parent=base, fontName=_FONT_BOLD, fontSize=16, leading=18),
        "stat_label": ParagraphStyle("stat_label", parent=base, fontSize=7.5, textColor=colors.HexColor(_MUTED)),
    }


def _risk(payload: dict, t: dict) -> tuple[str, str]:
    findings = payload.get("findings") or {}
    counts = {c: len(findings.get(c) or {}) for c in _CATEGORIES}
    content = payload.get("content_findings") or []
    critical_files = payload.get("critical_files") or []
    total = sum(counts.values())
    sensitive = counts["usernames"] + counts["emails"] + counts["internal_paths"] + counts["servers_and_printers"] + len(critical_files)
    critical_content = sum(1 for f in content if f.get("category") in _CRITICAL_CONTENT)

    if total == 0 and not content and not critical_files:
        return t["risk_none"], _MUTED
    if critical_content or counts["geolocation"] or _restricted_labels(payload):
        return t["risk_high"], _BAD
    if sensitive == 0 and not content:
        return t["risk_low"], _ACCENT
    if sensitive <= 10:
        return t["risk_medium"], _WARN
    return t["risk_high"], _BAD


def _restricted_labels(payload: dict) -> list[str]:
    labels = (payload.get("findings") or {}).get("classification_labels") or {}
    return [v for v in labels if _RESTRICTED_LABEL_RE.search(v)]


def _fmt_date(value: str) -> str:
    try:
        return datetime.fromisoformat(value).strftime("%Y-%m-%d %H:%M") + " UTC"
    except (TypeError, ValueError):
        return str(value or "-")


def _table(rows: list[list], widths: list[float], *, header_bg: str = "#f1f4f9") -> Table:
    table = Table(rows, colWidths=widths, repeatRows=1, hAlign="LEFT")
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(header_bg)),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor(_MUTED)),
        ("FONTNAME", (0, 0), (-1, 0), _FONT_BOLD),
        ("FONTSIZE", (0, 0), (-1, 0), 7.5),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LINEBELOW", (0, 0), (-1, -1), 0.4, colors.HexColor(_LINE)),
        ("BOX", (0, 0), (-1, -1), 0.4, colors.HexColor(_LINE)),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    return table


def _stat_cards(payload: dict, t: dict, st: dict, width: float) -> Table:
    findings = payload.get("findings") or {}
    docs = payload.get("documents") or []
    cards = [
        (str(len(findings.get("usernames") or {})), t["usernames"]),
        (str(len(findings.get("emails") or {})), t["emails"]),
        (str(len(findings.get("software") or {})), t["software"]),
        (str(len(findings.get("operating_systems") or {})), t["operating_systems"]),
        (str(len(findings.get("internal_paths") or {})), t["internal_paths"]),
        (str(len(findings.get("servers_and_printers") or {})), t["servers_and_printers"]),
        (str(payload.get("documents_discovered", len(docs))), t["stat_documents"]),
        (str(payload.get("documents_with_metadata", 0)), t["stat_with_metadata"]),
    ]
    cells = [[Paragraph(num, st["stat_num"]), Paragraph(label, st["stat_label"])] for num, label in cards]
    rows = [[_card(cells[i + j]) for j in range(4)] for i in range(0, 8, 4)]
    table = Table(rows, colWidths=[width / 4] * 4, hAlign="LEFT")
    table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    return table


def _card(cell: list) -> Table:
    inner = Table([[cell[0]], [cell[1]]], hAlign="LEFT")
    inner.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor(_LINE)),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (0, 0), 7),
        ("BOTTOMPADDING", (0, -1), (-1, -1), 7),
    ]))
    return inner


def _findings_section(payload: dict, category: str, t: dict, st: dict, width: float) -> list:
    bucket = (payload.get("findings") or {}).get(category) or {}
    story = [Paragraph(f"{t[category]} <font color='{_MUTED}'>({len(bucket)})</font>", st["h2"])]
    if not bucket:
        story.append(Paragraph(t["empty"], st["muted"]))
        return story

    if category == "classification_labels" and _restricted_labels(payload):
        story.append(Paragraph(f"<font color='{_BAD}'>{t['restricted_note']}</font>", st["body"]))
        story.append(Spacer(1, 4))

    rows = [[t["col_value"], t["col_field"], t["col_docs"], t["col_seen"]]]
    for value, meta in list(bucket.items())[:_MAX_ROWS]:
        urls = meta.get("document_urls") or []
        rows.append([
            Paragraph(_esc(value), st["cell_mono"]),
            Paragraph(_esc(meta.get("field_name") or "-"), st["cell"]),
            Paragraph(str(len(urls)), st["cell"]),
            Paragraph(_esc(urls[0]) if urls else "-", st["cell_mono"]),
        ])
    story.append(_table(rows, [width * 0.38, width * 0.16, width * 0.06, width * 0.40]))
    if len(bucket) > _MAX_ROWS:
        story.append(Paragraph(t["truncated"].format(n=len(bucket) - _MAX_ROWS), st["muted"]))
    return story


def _esc(value) -> str:
    return (str(value).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def _documents_section(payload: dict, t: dict, st: dict, width: float) -> list:
    docs = payload.get("documents") or []
    story = [Paragraph(f"{t['documents']} <font color='{_MUTED}'>({len(docs)})</font>", st["h2"])]
    archived = [d for d in docs if d.get("archive_url")]
    if archived:
        story.append(Paragraph(t["archive_note"].format(n=len(archived)), st["muted"]))
        story.append(Spacer(1, 4))

    rows = [[t["col_url"], t["col_type"], t["col_status"]]]
    for d in docs[:_MAX_ROWS]:
        url = _esc(d.get("url"))
        if d.get("archive_url"):
            url += f" <font color='{_WARN}' size='6.5'>[{t['archive_tag']}]</font>"
        if d.get("error"):
            status = f"<font color='{_BAD}'>{t['status_error']}: {_esc(d['error'])}</font>"
        else:
            status = f"<font color='{_GOOD}'>{t['status_ok']}</font>"
        rows.append([
            Paragraph(url, st["cell_mono"]),
            Paragraph(_esc(d.get("filetype")), st["cell"]),
            Paragraph(status, st["cell"]),
        ])
    story.append(_table(rows, [width * 0.60, width * 0.08, width * 0.32]))
    if len(docs) > _MAX_ROWS:
        story.append(Paragraph(t["truncated"].format(n=len(docs) - _MAX_ROWS), st["muted"]))
    return story


def _optional_sections(payload: dict, t: dict, st: dict, width: float) -> list:
    story = []
    content = payload.get("content_findings") or []
    if content:
        story.append(Paragraph(f"{t['content_scan']} <font color='{_MUTED}'>({len(content)})</font>", st["h2"]))
        story.append(Paragraph(t["content_note"], st["muted"]))
        story.append(Spacer(1, 4))
        rows = [[t["col_category"], t["col_masked"], t["col_document"]]]
        for f in content[:_MAX_ROWS]:
            rows.append([
                Paragraph(_esc(f.get("category")), st["cell"]),
                Paragraph(_esc(f.get("masked_value")), st["cell_mono"]),
                Paragraph(_esc(f.get("document_url")), st["cell_mono"]),
            ])
        story.append(_table(rows, [width * 0.16, width * 0.30, width * 0.54]))

    critical = payload.get("critical_files") or []
    if critical:
        story.append(Paragraph(f"{t['critical_files']} <font color='{_MUTED}'>({len(critical)})</font>", st["h2"]))
        rows = [[t["col_url"], t["col_type"], t["col_status"]]]
        for f in critical[:_MAX_ROWS]:
            rows.append([
                Paragraph(_esc(f.get("url")), st["cell_mono"]),
                Paragraph(_esc(f.get("filetype")), st["cell"]),
                Paragraph(_esc(f.get("error") or t["status_ok"]), st["cell"]),
            ])
        story.append(_table(rows, [width * 0.60, width * 0.08, width * 0.32]))

    errors = payload.get("errors") or []
    if errors:
        story.append(Paragraph(f"{t['errors']} <font color='{_MUTED}'>({len(errors)})</font>", st["h2"]))
        story.append(Paragraph(t["errors_note"], st["muted"]))
        story.append(Spacer(1, 4))
        rows = [[t["col_document"]]]
        for e in errors[:_MAX_ROWS]:
            rows.append([Paragraph(_esc(e), st["cell_mono"])])
        story.append(_table(rows, [width]))
        if len(errors) > _MAX_ROWS:
            story.append(Paragraph(t["truncated"].format(n=len(errors) - _MAX_ROWS), st["muted"]))
    return story


def render_pdf_report(payload: dict, lang: str = "en") -> bytes:
    """Build the PDF for one run, from its report.json payload."""
    if not PDF_AVAILABLE:
        raise PdfDependencyMissing(
            "PDF reports need the optional [pdf] extra: pip install 'metascout[pdf]'"
        )
    if lang not in _SUPPORTED_LANGS:
        raise ValueError(f"Unsupported report language '{lang}', expected one of {sorted(_SUPPORTED_LANGS)}")

    from .. import __version__

    _register_fonts()
    t = _STRINGS[lang]
    st = _styles()
    buffer = io.BytesIO()
    margin = 16 * mm
    width = A4[0] - 2 * margin

    doc = BaseDocTemplate(
        buffer, pagesize=A4,
        leftMargin=margin, rightMargin=margin, topMargin=margin, bottomMargin=18 * mm,
        title=f"MetaScout — {', '.join(payload.get('targets') or [])}", author="MetaScout",
    )
    frame = Frame(margin, 18 * mm, width, A4[1] - margin - 18 * mm, id="body", showBoundary=0)

    def decorate(canvas, _doc):
        canvas.saveState()
        canvas.setFont(_FONT, 7)
        canvas.setFillColor(colors.HexColor(_MUTED))
        canvas.drawString(margin, 11 * mm, t["footer"].format(version=f"v{__version__}"))
        canvas.drawRightString(A4[0] - margin, 11 * mm, t["page"].format(page=canvas.getPageNumber()))
        canvas.setStrokeColor(colors.HexColor(_LINE))
        canvas.line(margin, 14 * mm, A4[0] - margin, 14 * mm)
        canvas.restoreState()

    doc.addPageTemplates([PageTemplate(id="main", frames=[frame], onPage=decorate)])

    findings = payload.get("findings") or {}
    total_findings = sum(len(findings.get(c) or {}) for c in _CATEGORIES)
    risk_label, risk_color = _risk(payload, t)
    targets = ", ".join(payload.get("targets") or []) or "-"

    story = [
        Paragraph(t["title"], st["title"]),
        Paragraph(t["subtitle"], st["subtitle"]),
    ]
    head_rows = [[
        Paragraph(f"<b>{t['targets']}:</b> {_esc(targets)}<br/>"
                  f"<b>{t['scanned']}:</b> {_fmt_date(payload.get('scanned_at'))}<br/>"
                  f"<b>{t['generated']}:</b> {datetime.now().strftime('%Y-%m-%d %H:%M')}", st["body"]),
        Paragraph(f"<font color='{risk_color}' size='11'><b>{risk_label}</b></font>", st["body"]),
    ]]
    head = Table(head_rows, colWidths=[width * 0.72, width * 0.28], hAlign="LEFT")
    head.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ALIGN", (1, 0), (1, 0), "RIGHT"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("LINEBELOW", (0, 0), (-1, -1), 0.8, colors.HexColor(_LINE)),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    story += [head, Spacer(1, 10)]

    story.append(Paragraph(t["intro"].format(
        docs=payload.get("documents_discovered", len(payload.get("documents") or [])),
        with_meta=payload.get("documents_with_metadata", 0),
        findings=total_findings,
    ), st["body"]))
    story.append(Spacer(1, 8))
    story.append(_stat_cards(payload, t, st, width))

    by_target = payload.get("documents_by_target") or {}
    if len(by_target) > 1:
        rows = [[t["col_target"], t["col_documents"]]]
        rows += [[Paragraph(_esc(k), st["cell"]), Paragraph(str(v), st["cell"])] for k, v in by_target.items()]
        story += [Paragraph(t["per_target"], st["h2"]), _table(rows, [width * 0.7, width * 0.3])]

    for category in _CATEGORIES:
        story += _findings_section(payload, category, t, st, width)

    story += _optional_sections(payload, t, st, width)
    story.append(PageBreak())
    story += _documents_section(payload, t, st, width)

    doc.build(story)
    return buffer.getvalue()
